import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/antd.registry";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "bootstrap/dist/css/bootstrap.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={inter.className}
        style={{ backgroundColor: "#dedcd7", padding: "0" }}
      >
        <StyledComponentsRegistry>
          <Header />
          <div style={{ minHeight: "calc(100vh - 407px" }}>{children}</div>
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
